<?php
declare(strict_types=1);

namespace GatePay\CoreTests\Exceptions;

use GatePay\Core\Exceptions\UnsupportedModeException;
use GatePay\Core\Interfaces\GatewayInterface;
use GatePay\Example\DummyGateway\DummyGateway;
use GuzzleHttp\Psr7\HttpFactory;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use RuntimeException;

class UnsupportedModeExceptionTest extends TestCase
{
    private GatewayInterface $gateway;

    protected function setUp(): void
    {
        $this->gateway = new DummyGateway(new HttpFactory());
    }

    #[Test]
    public function constructorWithDefaultMessageSetsAutoGeneratedMessage(): void
    {
        $mode = 'sandbox';
        $exception = new UnsupportedModeException($this->gateway, $mode);

        $expectedMessage = "The mode 'sandbox' is not supported by the gateway 'DummyGateway'.";
        $this->assertSame($expectedMessage, $exception->getMessage());
    }

    #[Test]
    public function constructorWithCustomMessageSetsCustomMessage(): void
    {
        $mode = 'production';
        $customMessage = 'Custom unsupported mode message';
        $exception = new UnsupportedModeException($this->gateway, $mode, $customMessage);

        $this->assertSame($customMessage, $exception->getMessage());
    }

    #[Test]
    public function constructorWithEmptyMessageSetsAutoGeneratedMessage(): void
    {
        $mode = 'test';
        $exception = new UnsupportedModeException($this->gateway, $mode, '');

        $expectedMessage = "The mode 'test' is not supported by the gateway 'DummyGateway'.";
        $this->assertSame($expectedMessage, $exception->getMessage());
    }

    #[Test]
    public function constructorWithCodeSetsCode(): void
    {
        $exception = new UnsupportedModeException(
            $this->gateway,
            'sandbox',
            'Error',
            501
        );

        $this->assertSame(501, $exception->getCode());
    }

    #[Test]
    public function constructorWithPreviousExceptionSetsPrevious(): void
    {
        $previous = new RuntimeException('Previous error');
        $exception = new UnsupportedModeException(
            $this->gateway,
            'sandbox',
            'Error',
            0,
            $previous
        );

        $this->assertSame($previous, $exception->getPrevious());
    }

    #[Test]
    public function getGatewayReturnsCorrectGateway(): void
    {
        $mode = 'sandbox';
        $exception = new UnsupportedModeException($this->gateway, $mode);

        $this->assertSame($this->gateway, $exception->getGateway());
        $this->assertSame($this->gateway, $exception->gateway);
    }

    #[Test]
    public function getModeReturnsCorrectMode(): void
    {
        $mode = 'production';
        $exception = new UnsupportedModeException($this->gateway, $mode);

        $this->assertSame($mode, $exception->getMode());
        $this->assertSame($mode, $exception->mode);
    }

    #[Test]
    public function extendsRuntimeException(): void
    {
        $exception = new UnsupportedModeException($this->gateway, 'sandbox');

        $this->assertInstanceOf(RuntimeException::class, $exception);
    }

    #[Test]
    public function constructorWithAllParametersSetsAllProperties(): void
    {
        $mode = 'staging';
        $message = 'Complete error message';
        $code = 422;
        $previous = new RuntimeException('Inner exception');

        $exception = new UnsupportedModeException(
            $this->gateway,
            $mode,
            $message,
            $code,
            $previous
        );

        $this->assertSame($this->gateway, $exception->getGateway());
        $this->assertSame($mode, $exception->getMode());
        $this->assertSame($message, $exception->getMessage());
        $this->assertSame($code, $exception->getCode());
        $this->assertSame($previous, $exception->getPrevious());
    }

    #[Test]
    public function gatewayPropertyIsReadonly(): void
    {
        $exception = new UnsupportedModeException($this->gateway, 'sandbox');

        $reflection = new \ReflectionProperty($exception, 'gateway');

        $this->assertTrue($reflection->isReadOnly());
    }

    #[Test]
    public function modePropertyIsReadonly(): void
    {
        $exception = new UnsupportedModeException($this->gateway, 'sandbox');

        $reflection = new \ReflectionProperty($exception, 'mode');

        $this->assertTrue($reflection->isReadOnly());
    }

    #[Test]
    public function messageIncludesModeValue(): void
    {
        $modes = ['sandbox', 'production', 'development', 'testing'];

        foreach ($modes as $mode) {
            $exception = new UnsupportedModeException($this->gateway, $mode);
            $this->assertStringContainsString($mode, $exception->getMessage());
        }
    }

    #[Test]
    public function messageIncludesGatewayName(): void
    {
        $exception = new UnsupportedModeException($this->gateway, 'sandbox');

        $this->assertStringContainsString('DummyGateway', $exception->getMessage());
    }

    #[Test]
    public function supportsVariousModeStrings(): void
    {
        $modes = [
            'sandbox',
            'production',
            'live',
            'test',
            'development',
            'staging',
        ];

        foreach ($modes as $mode) {
            $exception = new UnsupportedModeException($this->gateway, $mode);
            $this->assertSame($mode, $exception->getMode());
        }
    }
}
