<?php
declare(strict_types=1);

namespace GatePay\CoreTests\Exceptions;

use GatePay\Core\Enum\GatewayAction;
use GatePay\Core\Exceptions\UnsupportedActionException;
use GatePay\Core\Interfaces\GatewayInterface;
use GatePay\Example\DummyGateway\DummyGateway;
use GuzzleHttp\Psr7\HttpFactory;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use RuntimeException;

class UnsupportedActionExceptionTest extends TestCase
{
    private GatewayInterface $gateway;

    protected function setUp(): void
    {
        $this->gateway = new DummyGateway(new HttpFactory());
    }

    #[Test]
    public function constructorWithDefaultMessageSetsAutoGeneratedMessage(): void
    {
        $action = GatewayAction::CHARGE;
        $exception = new UnsupportedActionException($this->gateway, $action);

        $expectedMessage = "The action 'CHARGE' is not supported by the gateway 'DummyGateway'.";
        $this->assertSame($expectedMessage, $exception->getMessage());
    }

    #[Test]
    public function constructorWithCustomMessageSetsCustomMessage(): void
    {
        $action = GatewayAction::REFUND;
        $customMessage = 'Custom unsupported action message';
        $exception = new UnsupportedActionException($this->gateway, $action, $customMessage);

        $this->assertSame($customMessage, $exception->getMessage());
    }

    #[Test]
    public function constructorWithEmptyMessageSetsAutoGeneratedMessage(): void
    {
        $action = GatewayAction::VOID;
        $exception = new UnsupportedActionException($this->gateway, $action, '');

        $expectedMessage = "The action 'VOID' is not supported by the gateway 'DummyGateway'.";
        $this->assertSame($expectedMessage, $exception->getMessage());
    }

    #[Test]
    public function constructorWithCodeSetsCode(): void
    {
        $exception = new UnsupportedActionException(
            $this->gateway,
            GatewayAction::CHARGE,
            'Error',
            501
        );

        $this->assertSame(501, $exception->getCode());
    }

    #[Test]
    public function constructorWithPreviousExceptionSetsPrevious(): void
    {
        $previous = new RuntimeException('Previous error');
        $exception = new UnsupportedActionException(
            $this->gateway,
            GatewayAction::CHARGE,
            'Error',
            0,
            $previous
        );

        $this->assertSame($previous, $exception->getPrevious());
    }

    #[Test]
    public function getGatewayReturnsCorrectGateway(): void
    {
        $action = GatewayAction::AUTHORIZE;
        $exception = new UnsupportedActionException($this->gateway, $action);

        $this->assertSame($this->gateway, $exception->getGateway());
        $this->assertSame($this->gateway, $exception->gateway);
    }

    #[Test]
    public function getActionReturnsCorrectAction(): void
    {
        $action = GatewayAction::CAPTURE;
        $exception = new UnsupportedActionException($this->gateway, $action);

        $this->assertSame($action, $exception->getAction());
        $this->assertSame($action, $exception->action);
    }

    #[Test]
    public function extendsRuntimeException(): void
    {
        $exception = new UnsupportedActionException($this->gateway, GatewayAction::TEST);

        $this->assertInstanceOf(RuntimeException::class, $exception);
    }

    #[Test]
    public function constructorWithAllParametersSetsAllProperties(): void
    {
        $action = GatewayAction::REFUND;
        $message = 'Complete error message';
        $code = 422;
        $previous = new RuntimeException('Inner exception');

        $exception = new UnsupportedActionException(
            $this->gateway,
            $action,
            $message,
            $code,
            $previous
        );

        $this->assertSame($this->gateway, $exception->getGateway());
        $this->assertSame($action, $exception->getAction());
        $this->assertSame($message, $exception->getMessage());
        $this->assertSame($code, $exception->getCode());
        $this->assertSame($previous, $exception->getPrevious());
    }

    #[Test]
    public function gatewayPropertyIsReadonly(): void
    {
        $exception = new UnsupportedActionException($this->gateway, GatewayAction::CHARGE);

        $reflection = new \ReflectionProperty($exception, 'gateway');

        $this->assertTrue($reflection->isReadOnly());
    }

    #[Test]
    public function actionPropertyIsReadonly(): void
    {
        $exception = new UnsupportedActionException($this->gateway, GatewayAction::CHARGE);

        $reflection = new \ReflectionProperty($exception, 'action');

        $this->assertTrue($reflection->isReadOnly());
    }

    #[Test]
    public function messageIncludesActionValue(): void
    {
        $actions = [
            GatewayAction::CHARGE,
            GatewayAction::REFUND,
            GatewayAction::VERIFY,
            GatewayAction::CANCEL,
        ];

        foreach ($actions as $action) {
            $exception = new UnsupportedActionException($this->gateway, $action);
            $this->assertStringContainsString($action->value, $exception->getMessage());
        }
    }

    #[Test]
    public function messageIncludesGatewayName(): void
    {
        $exception = new UnsupportedActionException($this->gateway, GatewayAction::CHARGE);

        $this->assertStringContainsString('DummyGateway', $exception->getMessage());
    }
}
